<a href="https://colab.research.google.com/github/Janhavi4230/Optional-Task-3/blob/main/Optional_Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import files
uploaded=files.upload()

Saving diamonds.csv to diamonds.csv

In [4]:
filepath='/content/diamonds.csv'
df=pd.read_csv(filepath)

In [5]:
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [6]:
df.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='object')

In [8]:
# Feature and Target

In [7]:
x=df.drop("price",axis=1)
y=df["price"]

In [9]:
# One Hot Encoding

In [11]:
x = pd.get_dummies(x, drop_first=True)

In [33]:
# Scale training and testing data

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
# Split dataset

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [23]:
# Train model

In [42]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [26]:
# Make predictions

In [27]:
y_pred = model.predict(x_test)

In [28]:
y_test

1388      559
50052    2201
41645    1238
42377    1304
17244    6901
         ...
44081    1554
23713     633
31375     761
21772    9836
4998     3742
Name: price, Length: 10788, dtype: int64

In [30]:
y_pred = model.predict(x_test)

print("Model created successfully!")
print("First 5 predicted prices:")
print(y_pred[:5])

Model created successfully!
First 5 predicted prices:
[ 508.31603663 3300.12577851 1985.5312597  2125.52304866 9876.87453928]

In [37]:
# Calculate R² Score

In [43]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: 0.9193399796988827

In [31]:
# Save the trained model

In [32]:
import joblib

joblib.dump(model, "diamond_price_model.pkl")

print("Model saved successfully!")

Model saved successfully!